#!/usr/bin/env bash
SELF_PATH="$(cd -P -- "$(dirname -- "$0")" && pwd -P)/$(basename -- "$0")"
SELF_PATH="$(readlink "$SELF_PATH" || echo $SELF_PATH)"
DIR_PATH="$(dirname "$SELF_PATH")"

cd $DIR_PATH
../node_modules/.bin/eslint ../src --fix

old_exit_code=$?
if [ !"$old_exit_code" -eq "0" ]; then
  echo "Shit! Error Happened: eslint" >&2
  ?=$old_exit_code
fi